services:
  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - api

  admin:
    build: ./admin
    env_file:
      - ./admin/.env
    ports:
      - "3001:3001"
    depends_on:
      - api

  api:
    build: ./api
    env_file:
      - ./api/.env.production
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mongo:6
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

volumes:
  db-data:
