name: Deploy to Now Noow VPS

on:
  push:
    branches: [ "main" ]  # deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/apps
            git reset --hard HEAD              
            git pull origin main
            docker-compose down
            docker-compose up -d --build
